ccflags-y += -Idrivers/media/platform/msm/camera_ferrari_v2
ccflags-y += -Idrivers/media/platform/msm/camera_ferrari_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_ferrari_v2/sensor/flash
obj-$(CONFIG_MSMB_CAMERA_SENSOR_FLASH_LM3646) += lm3646.o
obj-$(CONFIG_MSMB_CAMERA_SENSOR_FLASH_LM3646_DUMMY) += lm3646_dummy.o
